# Generated by Django 3.0.5 on 2020-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200417_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descreption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
